# Generated by Django 4.2.1 on 2023-05-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_page',
            name='matn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='home_page',
            name='matneng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='home_page',
            name='matnru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
