# Generated by Django 4.2.1 on 2023-05-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_remove_video_matn_remove_video_matneng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faoliyat_joy',
            name='rasm',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='hamkor',
            name='rasm',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='haqida_toliq',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='home_page',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ijtimoiy_tarmoq_url',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='maqola',
            name='rasm1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='maqola',
            name='rasm10',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='maqola',
            name='rasm2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='maqola',
            name='rasm3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='maqola',
            name='rasm4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='maqola',
            name='rasm5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='maqola',
            name='rasm6',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='maqola',
            name='rasm7',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='maqola',
            name='rasm8',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='maqola',
            name='rasm9',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
